### ISSUE TITLE
A tab per mutation status

### ISSUE THREAD

**Issue by 0xB10C** [aureleoules/bcm-ui#1]
The list of mutations get's long really fast. I think, splitting up the different tables in tabs would be nice.

Currently:
```
NotKilled (115)
Running (0)
Pending (1)
...
```

With tabs:
```
Not Killed (115) | Running (0) | Pending(1) | ...
```

like:

![Screenshot_20221202-090800.png](https://user-images.githubusercontent.com/19157360/205245846-a73576e8-cf1a-4004-b047-a45d7ed0d611.png)

**Comment by aureleoules** [comment]
Thanks for your suggestion, I added it!
